#!/usr/bin/env python

import sys


from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

if len(sys.argv) != 2:
    print("Usage: spos [FILE]")

try:
    with open(sys.argv[1]) as f:
        struct = Structure.from_file(sys.argv[1])
except IOError:
    print("Error: {} not found".format(sys.argv[1]))

print "Initial structure has {} atoms".format(struct.num_sites)

sym = SpacegroupAnalyzer(struct, symprec=1e-3)
#sym = SpacegroupAnalyzer(struct)
#print sym.get_symmetry_dataset()
#prim = sym.get_conventional_standard_structure()
prim = sym.find_primitive()
print "Final structure has {} atoms".format(prim.num_sites)
prim.to(filename="{}_prim".format(sys.argv[1]), fmt="poscar")
