#!/usr/bin/env python

import sys

from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

if len(sys.argv) != 2:
    print("Usage: spos [FILE]")

try:
    with open(sys.argv[1]) as f:
        struct = Structure.from_file(sys.argv[1])
except IOError:
    print("Error: {} not found".format(sys.argv[1]))

sym = SpacegroupAnalyzer(struct, )
print "Structure has the space group: {}".format(sym.get_space_group_symbol())
print "Structure is: {}".format(sym.get_lattice_type())
