#!/usr/bin/env python

import sys
import argparse

from pymatgen.core.structure import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

parser = argparse.ArgumentParser()
parser.add_argument('-f', '--file', help='path to input file', default='POSCAR',
                    type=str)
parser.add_argument('-t', '--tol', help='symmetry tolerance (default 1e-3)',
                    default=1e-3, type=float)
args = parser.parse_args()

struct = Structure.from_file(args.file)
sym = SpacegroupAnalyzer(struct, symprec=args.tol)
data = sym.get_symmetry_dataset()

print "Space group number: {}".format(data['number'])
print "International symbol: {}".format(data['international'])
print "Lattice type: {}".format(sym.get_lattice_type())
